/** Export a shareable Markdown or self-contained HTML report. */
import type { Analysis } from '../engine/analyze'
import { FORMAT_LABELS } from '../engine/importers'
import { redactText } from '../engine/redact'
import { roastFinding } from '../engine/roast'
import { fmtMs, fmtNum, fmtUsd } from '../engine/util'
import { SITE_URL } from './certificate'

export interface ReportOptions {
  redact: boolean
  roast: boolean
}

export function reportMarkdown(a: Analysis, opts: ReportOptions): string {
  const r = (s: string) => (opts.redact ? redactText(s).text : s)
  const v = a.verdict
  const lines = [
    `# Agent Autopsy — ${r(a.trace.name)}`,
    '',
    `> **${v.status === 'alive' ? 'Pronounced ALIVE' : v.status === 'injured' ? 'Survived with injuries' : 'Deceased'}** · Cause: ${r(v.cause)}${v.timeOfDeath !== undefined && v.status !== 'alive' ? ` · Time of death: T+${fmtMs(v.timeOfDeath)} (step ${v.step ?? '?'} of ${v.steps})` : ''}`,
    '',
    '| Grade | Health | Agent IQ | Efficiency | Cost | Wasted | Tokens | Duration | Format |',
    '|---|---|---|---|---|---|---|---|---|',
    `| **${a.grade}** | ${a.health}/100 | ${a.iq} | ${Math.round(a.efficiency * 100)}% | ${fmtUsd(a.totalCost)} | ${fmtUsd(a.wastedUsd)} (${fmtNum(a.wastedTokens)} tok) | ${fmtNum(a.totalTokens)} | ${fmtMs(a.duration)}${a.trace.timingEstimated ? ' (est.)' : ''} | ${FORMAT_LABELS[a.trace.format]} |`,
    '',
    `## Findings (${a.findings.length})`,
    '',
  ]
  if (!a.findings.length) lines.push('No issues found. 🎉', '')
  for (const f of a.findings) {
    lines.push(
      `### [${f.severity.toUpperCase()}] ${r(f.title)}`,
      '',
      r(f.detail),
      '',
      `**Fix:** ${f.fix}`,
    )
    if (f.wastedTokens)
      lines.push('', `_Waste: ~${fmtNum(f.wastedTokens)} tokens (${fmtUsd(f.wastedUsd ?? 0)})_`)
    if (opts.roast) lines.push('', `> 🌶️ ${r(roastFinding(f, a.trace.id))}`)
    lines.push('')
  }
  lines.push(
    '## Cost by model',
    '',
    '| Model | Calls | Input | Output | Cached | Cost |',
    '|---|---|---|---|---|---|',
  )
  for (const m of a.models)
    lines.push(
      `| ${m.model} | ${m.calls} | ${fmtNum(m.inputTokens)} | ${fmtNum(m.outputTokens)} | ${fmtNum(m.cachedTokens)} | ${fmtUsd(m.cost)} |`,
    )
  lines.push(
    '',
    '## Steps',
    '',
    '| # | Kind | Name | Duration | Tokens in/out | Status |',
    '|---|---|---|---|---|---|',
  )
  a.trace.spans
    .filter((s) => s.kind !== 'agent' && s.kind !== 'chain')
    .forEach((s, i) => {
      lines.push(
        `| ${i + 1} | ${s.kind} | ${r(s.toolName ?? s.name).replace(/\|/g, '\\|')} | ${fmtMs(s.end - s.start)} | ${s.kind === 'llm' ? `${fmtNum(s.inputTokens ?? 0)}/${fmtNum(s.outputTokens ?? 0)}` : ''} | ${s.status === 'error' ? '❌' : '✅'} |`,
      )
    })
  lines.push(
    '',
    `---`,
    `Generated by [Agent Autopsy](${SITE_URL}) — runs entirely in your browser.${opts.redact ? ' Secrets & PII redacted.' : ''}`,
  )
  return lines.join('\n')
}

function esc(s: string): string {
  return s.replace(
    /[&<>"]/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]!,
  )
}

/** Minimal markdown → HTML for our own report output (headings, tables, quotes, bold, code). */
export function reportHtml(a: Analysis, opts: ReportOptions): string {
  const md = reportMarkdown(a, opts)
  const inline = (s: string) =>
    esc(s)
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/_(.+?)_/g, '<em>$1</em>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
  const out: string[] = []
  const rows = md.split('\n')
  for (let i = 0; i < rows.length; i++) {
    const l = rows[i]
    if (l.startsWith('|')) {
      const table: string[] = []
      while (i < rows.length && rows[i].startsWith('|')) table.push(rows[i++])
      i--
      const cells = (row: string) =>
        row
          .slice(1, -1)
          .split(/(?<!\\)\|/)
          .map((c) => inline(c.trim().replace(/\\\|/g, '|')))
      out.push(
        `<table><thead><tr>${cells(table[0])
          .map((c) => `<th>${c}</th>`)
          .join('')}</tr></thead><tbody>${table
          .slice(2)
          .map(
            (r) =>
              `<tr>${cells(r)
                .map((c) => `<td>${c}</td>`)
                .join('')}</tr>`,
          )
          .join('')}</tbody></table>`,
      )
    } else if (l.startsWith('### ')) out.push(`<h3>${inline(l.slice(4))}</h3>`)
    else if (l.startsWith('## ')) out.push(`<h2>${inline(l.slice(3))}</h2>`)
    else if (l.startsWith('# ')) out.push(`<h1>${inline(l.slice(2))}</h1>`)
    else if (l.startsWith('> ')) out.push(`<blockquote>${inline(l.slice(2))}</blockquote>`)
    else if (l === '---') out.push('<hr/>')
    else if (l.trim()) out.push(`<p>${inline(l)}</p>`)
  }
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>Agent Autopsy — ${esc(opts.redact ? redactText(a.trace.name).text : a.trace.name)}</title>
<style>body{font:15px/1.55 -apple-system,Segoe UI,Inter,sans-serif;background:#0b0c10;color:#e5e7eb;max-width:980px;margin:40px auto;padding:0 20px}h1{font-size:28px}h2{margin-top:32px;border-bottom:1px solid #222;padding-bottom:6px}h3{font-size:16px;margin:22px 0 4px}table{border-collapse:collapse;width:100%;font-size:13px;margin:8px 0}th,td{border:1px solid #23262f;padding:6px 8px;text-align:left}th{background:#14161c}blockquote{border-left:3px solid #f43f5e;margin:10px 0;padding:6px 14px;background:#14161c;color:#fda4af}code{background:#1c1f27;padding:1px 5px;border-radius:4px}a{color:#67e8f9}</style></head><body>${out.join('\n')}</body></html>`
}

export function download(filename: string, content: string | Blob, type = 'text/plain'): void {
  const blob = typeof content === 'string' ? new Blob([content], { type }) : content
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 2000)
}
